# docker-compose up --build
# in order to add latest changes to the img
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
    ports:
      - "5005:5000"
    # command: ["ls", "-r"]
    command: ["python3", "-m", "api.v1.app"]
