# prepare builder stage of image
FROM node:alpine as builder
# set working directory
WORKDIR '/app'
# copy files to build image
COPY ./frontend/package.json ./
RUN npm install
# split run/copy cmds to cache the packages version of the image
COPY ./frontend ./
# run the npm deploy script in package.json
RUN npm run deploy


# production stage, use the files built
FROM nginx:alpine
# TODO fix how its build and copied
COPY --from=builder /app/lib /user/share/nginx/html